# Use root/example as user/password credentials
# Ports:
# WA : 80
# API: 8000
# USER: 8001

version: '3.1'

services:
  api:
    image: ansep/ansep_api
    restart: always
    container_name: api
    environment:
     - FRONT_END_PROTOCOL=${FRONTEND_PROTOCOL}
     - FRONT_END_HOST=${FRONTEND_HOST}
     - FRONT_END_PORT=${FRONTEND_PORT}
     - USER_MS_HOST=${USER_MS_HOST}
     - USER_MS_PORT=${USER_MS_PORT}
     - R_MS_HOST=${R_MS_HOST}
     - R_MS_PORT=${R_MS_PORT}
     - DOCKER_API_VERSION=${DOCKER_API_VERSION}
    ports:
      - "8000:8000"

  